CONDOR_DIR: ''
DATASET:
  BATCH_SIZE: 32
  NORMALIZE_IMAGES: true
  NUM_WORKERS: 8
EXP_NAME: lora_deco_dino_backbone_1_enc
LOGDIR: lora_deco_dino_backbone_1_enc/20-05-2025_09-48-45_lora_deco_dino_backbone_1_enc
OPTIMIZER:
  LR: 1.0e-05
  NUM_UPDATE_LR: 30
  TYPE: adam
OUTPUT_DIR: lora_deco_dino_backbone_1_enc
PROJECT_NAME: DECO_demo_training
TRAINING:
  BEST_MODEL_PATH: ./checkpoints/Other_Checkpoints/lora_deco_dino_backbone_1_enc_best.pth
  CHECKPOINT_EPOCHS: 50
  CLASSIFIER_TYPE: shared
  CONTEXT: true
  DATASETS:
  - damon
  DATASET_MIX_PDF:
  - '1.0'
  DATASET_ROOT_PATH: ''
  ENCODER: dinov2-giant
  LOSS_WEIGHTS: 1.0
  MODEL_TYPE: deco
  NUM_EARLY_STOP: 50
  NUM_ENCODER: 1
  NUM_EPOCHS: 100
  PAL_LOSS_WEIGHTS: 0.01
  SEMANTIC_CLASSIFIER: true
  SHARED_SEMANTIC_CLASSIFIER: true
  SUMMARY_STEPS: 5
  TRAIN_BACKBONE: true
VALIDATION:
  DATASETS:
  - damon
  MAIN_DATASET: damon
  SUMMARY_STEPS: 5
