EXP_NAME: 'hot_exp_test'
PROJECT_NAME: 'DECO_HOT_Testing'
OUTPUT_DIR: 'deco_results'
CONDOR_DIR: '/is/cluster/work/stripathi/pycharm_remote/dca_contact/condor/'
DATASET:
  BATCH_SIZE: 4
  NUM_WORKERS: 8
  NORMALIZE_IMAGES: False
OPTIMIZER:
  TYPE: 'adam'
  LR: [1e-5]
  NUM_UPDATE_LR: 3
TRAINING:
  ENCODER: 'hrnet'
  CONTEXT: [True]
  NUM_EPOCHS: 2
  NUM_EARLY_STOP: 10
  SUMMARY_STEPS: 5
  CHECKPOINT_EPOCHS: 5
  DATASETS: ['hot', 'rich']
  DATASET_MIX_PDF: ['0.5', '0.5'] # should sum to 1.0 unless you want to weight by dataset size
  DATASET_ROOT_PATH: '/is/cluster/work/stripathi/pycharm_remote/dca_contact/data/dataset_extras'
  BEST_MODEL_PATH: '/is/cluster/work/stripathi/pycharm_remote/dca_contact/weights/hot/exp/hot_exp.pth'
  LOSS_WEIGHTS: 1.
  PAL_LOSS_WEIGHTS: 0.0
VALIDATION:
  SUMMARY_STEPS: 5
  DATASETS: ['hot', 'rich']
  MAIN_DATASET: 'hot'
