EXP_NAME: 'damon_hrnet_testing'
PROJECT_NAME: 'DECO_DAMON_Testing'
OUTPUT_DIR: 'deco_results'
CONDOR_DIR: ''
DATASET:
  BATCH_SIZE: 16
  NUM_WORKERS: 4
  NORMALIZE_IMAGES: [True]
OPTIMIZER:
  TYPE: 'adam'
  LR: [5e-5]
  NUM_UPDATE_LR: 3
TRAINING:
  ENCODER: 'dinov2-giant'
  NUM_ENCODER: 2
  MODEL_TYPE: "dinoContact"
  CONTEXT: [False]
  NUM_EPOCHS: 100
  NUM_EARLY_STOP: 50
  SUMMARY_STEPS: 5
  CHECKPOINT_EPOCHS: 20
  DATASETS: ['damon']
  DATASET_MIX_PDF: ['1.0'] # should sum to 1.0 unless you want to weight by dataset size
  DATASET_ROOT_PATH: ''
  BEST_MODEL_PATH: './checkpoints/Other_Checkpoints/dino-contact-for-real(other_one_is_baseline)_best.pth'
  PAL_LOSS_WEIGHTS: 0.0
  SEMANTIC_CLASSIFIER: True
  SHARED_SEMANTIC_CLASSIFIER: True
  CLASSIFIER_TYPE: "shared"
  TRAIN_BACKBONE: False #only for DINO backbone
VALIDATION:
  SUMMARY_STEPS: 1000
  DATASETS: ['damon']
  MAIN_DATASET: 'damon'