EXP_NAME: 'deco_shared_classifier'
PROJECT_NAME: 'DECO_demo_training'
OUTPUT_DIR: 'deco_results'
CONDOR_DIR: ''
DATASET:
  BATCH_SIZE: 16
  NUM_WORKERS: 8
  NORMALIZE_IMAGES: [True]
OPTIMIZER:
  TYPE: 'adam'
  LR: [1e-5]
  NUM_UPDATE_LR: 3
TRAINING:
  ENCODER: 'dinov2'
  CONTEXT: [True]
  NUM_EPOCHS: 100
  NUM_EARLY_STOP: 10
  SUMMARY_STEPS: 5
  CHECKPOINT_EPOCHS: 5
  DATASETS: ['damon']
  DATASET_MIX_PDF: ['1.0'] # should sum to 1.0 unless you want to weight by dataset size
  DATASET_ROOT_PATH: ''
  BEST_MODEL_PATH: './checkpoints/Other_Checkpoints/deco_shared_classifier.pth'
  LOSS_WEIGHTS: 1.
  PAL_LOSS_WEIGHTS: 0.01
  SEMANTIC_CLASSIFIER: False
  SHARED_SEMANTIC_CLASSIFIER: True
VALIDATION:
  SUMMARY_STEPS: 5
  DATASETS: ['damon']
  MAIN_DATASET: 'damon'
