CONDOR_DIR: ''
DATASET:
  BATCH_SIZE: 32
  NORMALIZE_IMAGES: true
  NUM_WORKERS: 8
EXP_NAME: dino-contact-for-real(other_one_is_baseline)
LOGDIR: dino-contact-for-real_results/17-05-2025_17-08-46_dino-contact-for-real(other_one_is_baseline)
OPTIMIZER:
  LR: 1.0e-05
  NUM_UPDATE_LR: 30
  TYPE: adam
OUTPUT_DIR: dino-contact-for-real_results
PROJECT_NAME: DECO_demo_training
TRAINING:
  BEST_MODEL_PATH: ./checkpoints/Other_Checkpoints/dino-contact-for-real(other_one_is_baseline)_best.pth
  CHECKPOINT_EPOCHS: 50
  CLASSIFIER_TYPE: shared
  CONTEXT: false
  DATASETS:
  - damon
  DATASET_MIX_PDF:
  - '1.0'
  DATASET_ROOT_PATH: ''
  ENCODER: dinov2-giant
  LOSS_WEIGHTS: 1.0
  MODEL_TYPE: dinoContact
  NUM_EARLY_STOP: 50
  NUM_ENCODER: 2
  NUM_EPOCHS: 100
  PAL_LOSS_WEIGHTS: 0.01
  SEMANTIC_CLASSIFIER: true
  SHARED_SEMANTIC_CLASSIFIER: true
  SUMMARY_STEPS: 5
  TRAIN_BACKBONE: false
VALIDATION:
  DATASETS:
  - damon
  MAIN_DATASET: damon
  SUMMARY_STEPS: 5
